name: Generate ASCII Workflow
on: push
jobs:
    ascii_generate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: List All the Files
              run: ls -ltra

            - name: Executing Shell Script
              run: ./ascii-script.sh